(ns net.wikipunk.punk.db.boot
  {:rdf/type :jsonld/Context}
  (:require
   [net.wikipunk.rdf.db]
   [net.wikipunk.rdf.db.alter]
   [net.wikipunk.rdf.db.attr]
   [net.wikipunk.rdf.db.bootstrap]
   [net.wikipunk.rdf.db.cardinality]
   [net.wikipunk.rdf.db.entity]
   [net.wikipunk.rdf.db.excise]
   [net.wikipunk.rdf.db.install]
   [net.wikipunk.rdf.db.part]
   [net.wikipunk.rdf.db.type]
   [net.wikipunk.rdf.db.unique]
   [net.wikipunk.rdf.as]
   [net.wikipunk.rdf.cc]
   [net.wikipunk.rdf.csvw]
   [net.wikipunk.rdf.ctag]
   [net.wikipunk.rdf.dc11]
   [net.wikipunk.rdf.dcat]
   [net.wikipunk.rdf.dcterms]
   [net.wikipunk.rdf.dqv]
   [net.wikipunk.rdf.duv]
   [net.wikipunk.rdf.foaf]
   [net.wikipunk.rdf.gr]
   [net.wikipunk.rdf.grddl]
   [net.wikipunk.rdf.cal]
   [net.wikipunk.rdf.formats]
   [net.wikipunk.rdf.jsonld]
   [net.wikipunk.rdf.ldp]
   [net.wikipunk.rdf.geo]
   [net.wikipunk.rdf.ontolex]
   [net.wikipunk.rdf.ma]
   [net.wikipunk.rdf.oa]
   [net.wikipunk.rdf.odrl]
   [net.wikipunk.rdf.og]
   [net.wikipunk.rdf.ogc]
   [net.wikipunk.rdf.org]
   [net.wikipunk.rdf.owl]
   [net.wikipunk.rdf.prov]
   [net.wikipunk.rdf.qb]
   [net.wikipunk.rdf.rdf]
   [net.wikipunk.rdf.rdfa]
   [net.wikipunk.rdf.rdfs]
   [net.wikipunk.rdf.rev]
   [net.wikipunk.rdf.rr]
   [net.wikipunk.rdf.schema]
   [net.wikipunk.rdf.sd]
   [net.wikipunk.rdf.sioc]
   [net.wikipunk.rdf.skos]
   [net.wikipunk.rdf.skosxl]
   [net.wikipunk.rdf.sosa]
   [net.wikipunk.rdf.ssn]
   [net.wikipunk.rdf.time]
   [net.wikipunk.rdf.vcard]
   [net.wikipunk.rdf.void]
   [net.wikipunk.rdf.wdrs]
   [net.wikipunk.rdf.xhv]
   [net.wikipunk.rdf.xsd]
   [net.wikipunk.rdf.punk.db]))

(def punk.db
  {:rdf/type    :rdfa/PrefixMapping
   :rdfa/uri    "https://wikipunk.net/punk/db/"
   :rdfa/prefix "punk.db"})
